### ISSUE TITLE
通知画面の一覧から、詳細へ飛ぼうとするとエラー

### ISSUE THREAD

**Issue by fumihisasuzuki** [taniryuu/Rer_Pro#103]
通知画面の一覧から、詳細へ飛ぼうとするとエラーになります。
Stepモデルにnotice_change_limitを追加したことによる不具合のようですので、ご対応いただけますと幸いです。
![image](https://user-images.githubusercontent.com/56940903/99451766-0c052980-2966-11eb-9eb8-e13ccf30117f.png)
![image](https://user-images.githubusercontent.com/56940903/99452126-833abd80-2966-11eb-8208-9b5c0681eb6b.png)

**Comment by taniryuu** [comment]
git pullした後
rails db:migrate:reset db:seedを実行してみてください。
確認しましたら私の環境だとエラーは出ませんのし、エラー文もnotice_change_limitカラムが存在しませんって書いてますのでDBを更新してみてください。

**Comment by fumihisasuzuki** [comment]
DB更新でうまくいきました！ありがとうございます。
