### ISSUE TITLE
通知の表記改善提案

### ISSUE THREAD

**Issue by fumihisasuzuki** [taniryuu/Rer_Pro#109]
案件詳細ページのこの画像の表記ですが、進捗名だけ表示されていると、何のことやらわからないので、「期限変更通知」など、何の「確認」なの？というのがわかりやすいような表示にできないでしょうか？？
![image](https://user-images.githubusercontent.com/56940903/100026569-643c9f80-2e2e-11eb-9b52-a5a0f1115bff.png)

**Comment by taniryuu** [comment]
ここの表示を作成するのはこの案件詳細ページの見た目と同時に作れば良いかなと
イメージにばらつきが出ないよう現状ロジックの作成に留めてます。

----期限変更---------------------------------------------------
期限変更通知:  進捗名　　　　　　　　   上長名　　確認ボタン
----------------------------------------------------------------

自分のイメージはflashメッセージの表示みたいに枠線で囲って上に表示
色は赤か黄？ですかね
この案件詳細ページの見た目がある程度イメージ固まってたらカスタマイズしていただいて大丈夫ですよ！

**Comment by fumihisasuzuki** [comment]
谷口さん、上記、コメント気づいていませんでした。申し訳ありません。
また、現状、leadとstepのテストを作成している段階のため、手が出ません。
重ねて申し訳ないのですが、上記、谷口さんのイメージで構いませんので、カスタマイズお願いできないでしょうか？？

**Comment by taniryuu** [comment]
わかりました〜
なるべくわかりやすくシンプル目に作成します。

**Comment by fumihisasuzuki** [comment]
谷口さん、ご対応ありがとうございました。
