### ISSUE TITLE
leads/steps#editページ→updateの流れ

### ISSUE THREAD

**Issue by taniryuu** [taniryuu/Rer_Pro#115]
テスト中に発見した不具合を報告します。
/steps/:id/edit(viewページleads/steps#edit)ページです。

進捗の完了予定日を変更した際に案件(lead)のnotice_change_limitがtrueに更新されるのですが、
進捗(step)のnotice_change_limitがtrueに更新されるロジックが含まれておらず、案件詳細ページで通知を確認することができなくなっております。

もう一点
進捗の更新時にタスクの入力はやはり必要ない気がします。
タスク欄を入力をしないとバリデーションが働いて編集できず、入力をしてもタスクに反映されないのはユーザー目線に立つと使いづらいと思いますので何かしら対策が必要かと思います。

**Comment by ruffini47** [comment]
https://github.com/taniryuu/Rer_Pro/pull/124
において修正対応しました。
ご確認ください。

**Comment by ruffini47** [comment]
「issue#115,#120,#121に対する修正」
#124
において直接進捗編集時、新規進捗作成時に進捗に「未」のタスクがある場合、新規タスク作成フォームを表示しないように変更しました。また、進捗ステータスとして「完了」、「未」を選んだ場合「タスク名」、「完了予定日」を空欄にしてもバリデーションエラーにならないように変更しました。
