### ISSUE TITLE
「期限変更」通知の確認ボタンについて。

### ISSUE THREAD

**Issue by fumihisasuzuki** [taniryuu/Rer_Pro#119]
@taniryuu さん

確認する権限のないユーザーが案件詳細を見る際は、この確認ボタンは非表示の方が良いのではないでしょうか。
そもそも、期限変更通知自体、非表示でも良いかもしれません。
どう思います？
![image](https://user-images.githubusercontent.com/56940903/101226086-b1462e80-36d6-11eb-93e2-12ba5ffa7d76.png)

**Comment by taniryuu** [comment]
期限変更通知の表示は必要だと思ってます。
期限の伸びや遅れは自分、通知受信者だけでなく企業内第三者でもこのページを開ける以上、共有できたほうがいい情報です。

確認ボタンについては正直こちら側が手動でif分岐テスト(指定のユーザーしか確認できない。)をしやすく置いてるだけです。
正直なところどちらでも良いのですが、確認ボタンを押して確認処理するロジックを
viewでif分岐させてボタンを消す+controller側で同じif分岐する動きをひとつのcontroller側のif分岐で済む気もします。

**Comment by fumihisasuzuki** [comment]
概略承知しました。
最後の１行

> viewでif分岐させてボタンを消す+controller側で同じif分岐する動きをひとつのcontroller側のif分岐で済む気もします。

がどういうことか、イマイチ理解できなかったので、もう少し詳しくご説明いただいてもよろしいでしょうか？

ユーザー視点だと、押せるボタンを押したら「権限がない」と言われるのは、「だったら最初から表示しないでほしい」となるような気がしたので、viewで非表示にするか、グレーアウト（readonly）にするのは必須かなと考えました。
また、controller側でif分岐するのは、悪意のあるユーザーがURLをいじって直接編集しようとした際にはじく必要があるので、viewでif分岐するのとはまた別に必要かなと考えています。
ただ、確かに、同じ条件が何度も出てくるのでしたら、うまくDRYにできる方法があるなら、取り入れたいですね！

**Comment by taniryuu** [comment]
ユーザー視点だと確かにボタンを押せないまたは隠す様に手を加える必要はありますね。

すぐ対応できるのでテスト段階である現状、このままでお願いします。
