### ISSUE TITLE
進捗を進めた上の挙動バグについて

### ISSUE THREAD

**Issue by taniryuu** [taniryuu/Rer_Pro#121]
edit_continue_or_destroy_step_task_path(/tasks/:id/edit_continue_or_destroy_step),
edit_complete_or_continue_step_path(/tasks/:id/edit_complete_or_continue_step),
edit_change_status_or_complete_task_path(/tasks/:id/edit_change_status_or_complete_task)
はそれぞれURLを直接入力すると進捗のステータスに関係なく表示されてしまいます。何かしら対策が必要かと思います。
・進捗のステータスでif分岐、それぞれviewテンプレートにわけて一つのviewに表示させるなど？

この件でもう一つ
URLの:id部分は一見するとタスクのIDなのですがstepのIDになってます。
それぞれ進捗のステータスで表示が変わるのなら
勘違いを生みやすいためstep/:id/~~~に変更したほうがいいかと思います。

**Comment by ruffini47** [comment]
issue#115,#120,#121に対する修正
#124
において修正対応しました。
ご確認ください。

**Comment by ruffini47** [comment]
「issue#115,#120,#121に対する修正」
#124
において直接URLを入力した場合、before_action check_statusを設定することにより、条件に合わない場合@stepに強制リダイレクトするようにしました。
その際の条件部分をcontinue_or_destroy_step?(step)、complete_or_continue_step?(step)、change_status_or_complete_task?(step)メソッドに切り出しました。
ルーティング/tasks/:id/edit_continue_or_destroy_step、/tasks/:id/edit_complete_or_continue_step、/tasks/:id/edit_change_status_or_complete_taskを/steps/:id/edit_continue_or_destroy_step、/steps/:id/edit_complete_or_continue_step、/steps/:id/edit_change_status_or_complete_taskに変更しました。その際、action、viewなどをtasksからstepsに移動しました。
