### ISSUE TITLE
Taskのアクションについて

### ISSUE THREAD

**Issue by taniryuu** [taniryuu/Rer_Pro#122]
ルーティングを見直していた時
edit_add_delete_list_task_path,
edit_revive_from_canceled_list_task_path
のURLが不具合を起こしています。
URLが多くて全て見れてないですがgetだけでも見直してみてください。
今後も使わない予定のアクション、ルーティングがあるなら削除お願いします。

**Comment by ruffini47** [comment]
edit_add_delete_list_task_path,
edit_revive_from_canceled_list_task_path
のURLがどう不具合を起こしているのでしょうか？
具体的に教えていただけませんか？
どちらも必要なアクション、ルーティングだと思っています。

**Comment by taniryuu** [comment]
DBのレコード新規作成時はpostが適しているのは存じているはずなので、
更新させる時はpatchのほうが適してます。
タスクのステータスを済、中止など更新させるアクションはpatchが適していると思います。
getはviewが存在してないと結構違和感を感じます。

これらのアクションが必要なのは理解しているのですが、、、
rails routesコマンドをターミナルで実行してみて各アクションを見返してみてください。
taskのindexファイルがviewテンプレートと2つあったりしてます。

**Comment by ruffini47** [comment]
「issue#115,#120,#121に対する修正」
#124
において、

**Comment by fumihisasuzuki** [comment]
コメントに書いてあるだけではダメなんでしょうか、うまくこちらもクローズしませんでしたね・・・

手動でクローズしておきます。
