### ISSUE TITLE
進捗の新規作成時、何も入力せずにsubmitすると@taskがNilClassエラー

### ISSUE THREAD

**Issue by fumihisasuzuki** [taniryuu/Rer_Pro#130]
@ruffini47 さん
タイトル通り、進捗の新規作成時、何も入力せずにsubmitすると、@taskがnilになっていると怒られます。
確認していただき、再現性あるようでしたら修正をお願いできますか？
![image](https://user-images.githubusercontent.com/56940903/102287144-250cf480-3f7d-11eb-938b-1a74ca7f1bdc.png)

git pull origin develop
や
rails db:migrate:reset
rails db:seed
は試してみましたが、上記再現性があります。

**Comment by taniryuu** [comment]
似た部類のエラーなので、このissueと一緒で構いません。
タスク登録失敗時にもエラーが発生するようになってます。
renderでtask#newに飛ぼうとしているのをstep_pathに設定しなおせばOKです。
確認お願いします。

**Comment by ruffini47** [comment]
pull request #133で自動で閉じなかったので、手動で閉じます。
